import { Link } from "react-router-dom";
import { Brain, Sparkles, Building2, ClipboardCheck, MessageSquare, ArrowRight, Zap, Target, TrendingUp, CheckCircle2, FileText, MessageCircleQuestion, Mic, Star, Code2, Users, Calendar, Trophy, BookOpen, Rocket, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import heroImage from "@/assets/hero-placement.jpg";
import showcaseImage from "@/assets/feature-showcase.jpg";

const features = [
  { icon: ClipboardCheck, title: "Smart Skill Assessment", desc: "Adaptive quiz across aptitude, coding & CS core that measures your real placement readiness in minutes.", color: "from-primary to-primary-glow" },
  { icon: Building2, title: "Company Drive Database", desc: "Past patterns, topics, difficulty & rounds for top recruiters — Google, Microsoft, Amazon, TCS, Infosys & more.", color: "from-secondary to-primary" },
  { icon: Sparkles, title: "Personalized AI Roadmap", desc: "Week-by-week prep plan generated by AI based on your skill gaps and target company.", color: "from-accent to-secondary" },
  { icon: MessageCircleQuestion, title: "AI Mock Interviews", desc: "Practice rounds tailored to your dream company — coding, system design & HR drills with instant feedback.", color: "from-primary-glow to-accent" },
  { icon: FileText, title: "Resume AI Reviewer", desc: "Get a 100-point ATS score, dimension breakdown & before/after rewrites in seconds.", color: "from-primary to-secondary" },
  { icon: Mic, title: "24/7 Voice AI Mentor", desc: "Ask doubts by voice or text — your senior who never sleeps, on call always.", color: "from-secondary to-accent" },
  { icon: Code2, title: "Coding Practice Hub", desc: "DSA problems sorted by company tags, with hints, solutions & complexity analysis.", color: "from-accent to-primary" },
  { icon: Trophy, title: "Aptitude Daily Drills", desc: "5-minute daily quant, logical & verbal practice with streaks and leaderboards.", color: "from-primary to-accent" },
  { icon: Users, title: "Group Discussion Simulator", desc: "AI-moderated GD rooms with topic generation, scoring on clarity, content & confidence.", color: "from-secondary to-primary-glow" },
];

const stats = [
  { value: "14+", label: "Companies tracked" },
  { value: "120+", label: "Topics covered" },
  { value: "9", label: "AI modules" },
  { value: "24/7", label: "Voice mentor" },
];

const problems = [
  "Same study material for everyone — zero personalization",
  "No clue what specific companies actually ask",
  "Wasting time on irrelevant topics with no roadmap",
  "No way to measure aptitude, coding & technical skills",
  "Stress and confusion lowering placement success",
];

const journey = [
  { step: "01", icon: ClipboardCheck, title: "Take the Assessment", desc: "Adaptive 20-min test scores you across aptitude, coding, CS core & communication." },
  { step: "02", icon: TrendingUp, title: "Get Your Placement Score", desc: "ML model predicts your placement probability and pinpoints the exact gaps." },
  { step: "03", icon: Sparkles, title: "Receive AI Roadmap", desc: "Personalized week-by-week plan mapped to your dream companies' patterns." },
  { step: "04", icon: Rocket, title: "Practice & Land the Offer", desc: "Mock interviews, resume reviews & voice mentor — until you crack the offer." },
];

const testimonials = [
  { name: "Aanya S.", role: "CSE, Final Year", text: "The ML probability score told me exactly where I stood. 4 weeks later — placed at a product company.", rating: 5 },
  { name: "Rohan M.", role: "IT, 3rd Year", text: "Mock interview rounds + the resume reviewer gave me confidence I never had before.", rating: 5 },
  { name: "Priya K.", role: "ECE, Final Year", text: "Insights page with real recruiter CTC data is gold. Knew exactly which companies to target.", rating: 5 },
];

export default function Landing() {
  return (
    <div className="min-h-screen bg-background relative overflow-hidden">
      {/* Ambient orbs */}
      <div className="pointer-events-none fixed inset-0 overflow-hidden -z-10">
        <div className="absolute -top-40 -left-40 h-[600px] w-[600px] rounded-full bg-primary/20 blur-3xl animate-orb" />
        <div className="absolute top-1/4 -right-40 h-[600px] w-[600px] rounded-full bg-secondary/15 blur-3xl animate-orb" style={{ animationDelay: "5s" }} />
        <div className="absolute bottom-0 left-1/3 h-[500px] w-[500px] rounded-full bg-accent/10 blur-3xl animate-orb" style={{ animationDelay: "10s" }} />
      </div>

      {/* Nav */}
      <header className="fixed top-0 z-40 w-full border-b border-border/30 glass-strong">
        <div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-3.5 sm:px-6">
          <Link to="/" className="flex items-center gap-2.5 group">
            <div className="relative flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-hero shadow-glow transition-bounce group-hover:scale-110">
              <Brain className="h-5 w-5 text-primary-foreground" />
            </div>
            <span className="font-display text-xl font-bold text-foreground">PlaceMentor <span className="text-gradient">Pro</span></span>
          </Link>
          <nav className="hidden items-center gap-7 md:flex">
            <a href="#features" className="text-sm text-foreground/80 hover:text-foreground transition-smooth">Features</a>
            <a href="#how" className="text-sm text-foreground/80 hover:text-foreground transition-smooth">How it works</a>
            <a href="#journey" className="text-sm text-foreground/80 hover:text-foreground transition-smooth">Journey</a>
            <a href="#testimonials" className="text-sm text-foreground/80 hover:text-foreground transition-smooth">Stories</a>
          </nav>
          <div className="flex items-center gap-2">
            <Link to="/auth"><Button variant="ghost" size="sm">Sign in</Button></Link>
            <Link to="/auth"><Button size="sm" className="bg-gradient-hero text-primary-foreground shadow-elegant hover:shadow-glow transition-smooth">Get Started <ArrowRight className="ml-1.5 h-3.5 w-3.5" /></Button></Link>
          </div>
        </div>
      </header>

      {/* Hero */}
      <section className="relative pt-36 pb-20 sm:pt-44 overflow-hidden">
        <div className="pointer-events-none absolute -top-20 left-1/2 h-[600px] w-[600px] -translate-x-1/2 bg-gradient-glow blur-3xl animate-glow-pulse" />

        <div className="relative mx-auto max-w-6xl px-4 sm:px-6">
          <div className="grid gap-12 lg:grid-cols-2 lg:items-center">
            {/* Left: copy */}
            <div className="text-center lg:text-left">
              <div className="mb-6 inline-flex animate-fade-in-up items-center gap-2 rounded-full glass px-4 py-1.5 text-xs font-medium">
                <span className="relative flex h-2 w-2">
                  <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-accent opacity-75" />
                  <span className="relative inline-flex h-2 w-2 rounded-full bg-accent" />
                </span>
                <span className="text-foreground/80">Powered by</span>
                <span className="text-gradient font-semibold">Gemini 2.5 + ML Models</span>
              </div>
              <h1 className="animate-fade-in-up font-display text-4xl font-bold leading-[1.05] tracking-tight sm:text-5xl md:text-6xl text-foreground" style={{ animationDelay: "0.1s" }}>
                Your AI <span className="text-gradient">Training & Placement</span> Coach
              </h1>
              <p className="mx-auto mt-6 max-w-xl animate-fade-in-up text-lg text-foreground/85 lg:mx-0" style={{ animationDelay: "0.2s" }}>
                One platform for everything — adaptive assessment, ML placement score, AI mock interviews, resume reviewer, coding practice, GD simulator & a 24/7 voice mentor. Built for students preparing for campus placements.
              </p>
              <div className="mt-10 flex animate-fade-in-up flex-col items-center justify-center gap-3 sm:flex-row lg:justify-start" style={{ animationDelay: "0.3s" }}>
                <Link to="/auth">
                  <Button size="lg" className="bg-gradient-hero text-primary-foreground shadow-elegant transition-bounce hover:scale-105 hover:shadow-glow">
                    Start Preparing Free <ArrowRight className="ml-2 h-4 w-4" />
                  </Button>
                </Link>
                <a href="#features"><Button size="lg" variant="outline" className="border-border/60 glass">Explore features</Button></a>
              </div>
              <div className="mt-6 flex animate-fade-in-up items-center justify-center gap-6 text-xs text-foreground/70 lg:justify-start" style={{ animationDelay: "0.4s" }}>
                <div className="flex items-center gap-1.5"><CheckCircle2 className="h-3.5 w-3.5 text-accent" /> No credit card</div>
                <div className="flex items-center gap-1.5"><CheckCircle2 className="h-3.5 w-3.5 text-accent" /> Free forever</div>
                <div className="flex items-center gap-1.5"><CheckCircle2 className="h-3.5 w-3.5 text-accent" /> 9 AI modules</div>
              </div>
            </div>

            {/* Right: hero image */}
            <div className="relative animate-fade-in-up" style={{ animationDelay: "0.25s" }}>
              <div className="absolute -inset-8 rounded-[2rem] bg-gradient-hero opacity-30 blur-3xl animate-glow-pulse" />
              <div className="relative overflow-hidden rounded-[1.75rem] border border-border/40 shadow-elegant">
                <img
                  src={heroImage}
                  alt="Students climbing career ladder with AI-powered placement training and analytics"
                  className="h-full w-full object-cover"
                  width={1920}
                  height={1080}
                  fetchPriority="high"
                />
                <div className="pointer-events-none absolute inset-0 bg-gradient-to-tr from-background/70 via-transparent to-transparent" />
                {/* Floating stat cards */}
                <div className="absolute left-4 top-4 animate-float rounded-2xl glass-strong px-4 py-3 shadow-neon">
                  <div className="flex items-center gap-2">
                    <Trophy className="h-4 w-4 text-accent" />
                    <div>
                      <div className="text-[10px] uppercase tracking-wider text-foreground/70">Placement Score</div>
                      <div className="font-display text-lg font-bold text-foreground">87%</div>
                    </div>
                  </div>
                </div>
                <div className="absolute bottom-4 right-4 animate-float rounded-2xl glass-strong px-4 py-3 shadow-neon" style={{ animationDelay: "1.5s" }}>
                  <div className="flex items-center gap-2">
                    <Sparkles className="h-4 w-4 text-secondary" />
                    <div>
                      <div className="text-[10px] uppercase tracking-wider text-foreground/70">AI Roadmap</div>
                      <div className="text-xs font-semibold text-foreground">12-week plan ready</div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Stats */}
          <div className="mx-auto mt-20 grid max-w-4xl animate-fade-in-up grid-cols-2 gap-4 sm:grid-cols-4" style={{ animationDelay: "0.5s" }}>
            {stats.map((s) => (
              <div key={s.label} className="gradient-border p-5 text-center hover-lift">
                <div className="font-display text-3xl font-bold text-gradient sm:text-4xl">{s.value}</div>
                <div className="mt-1 text-xs uppercase tracking-wider text-foreground/70">{s.label}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* What is this project */}
      <section className="border-t border-border/30 py-20">
        <div className="mx-auto max-w-6xl px-4 sm:px-6">
          <div className="grid gap-12 lg:grid-cols-2 lg:items-center">
            <div className="relative order-2 lg:order-1">
              <div className="absolute -inset-6 rounded-3xl bg-gradient-hero opacity-25 blur-3xl" />
              <div className="relative overflow-hidden rounded-3xl border border-border/40 shadow-elegant">
                <img
                  src={showcaseImage}
                  alt="Isometric view of placement training tools — coding, resume, interview, AI assistant"
                  className="h-full w-full object-cover"
                  loading="lazy"
                  width={1280}
                  height={896}
                />
              </div>
            </div>
            <div className="order-1 lg:order-2">
              <div className="mb-3 inline-flex items-center gap-2 rounded-full glass px-3 py-1 text-xs font-semibold text-secondary">
                <ShieldCheck className="h-3 w-3" /> One Platform · All-In-One
              </div>
              <h2 className="font-display text-4xl font-bold leading-tight text-foreground">
                What is <span className="text-gradient">PlaceMentor Pro?</span>
              </h2>
              <p className="mt-4 text-foreground/80 text-base leading-relaxed">
                It's a complete AI-powered training & placement OS for students. Instead of juggling 10 different sites — leetcode, geeksforgeeks, resume tools, mock interview platforms, aptitude apps — every module you need is integrated, personalized, and tracks your progress in one dashboard.
              </p>
              <div className="mt-6 grid grid-cols-2 gap-3">
                {[
                  { icon: ClipboardCheck, text: "Skill Assessment" },
                  { icon: TrendingUp, text: "Placement Predictor" },
                  { icon: Building2, text: "Company Database" },
                  { icon: Sparkles, text: "AI Prep Plan" },
                  { icon: MessageCircleQuestion, text: "Mock Interviews" },
                  { icon: FileText, text: "Resume Reviewer" },
                  { icon: Code2, text: "Coding Practice" },
                  { icon: Mic, text: "Voice Mentor" },
                ].map((m) => (
                  <div key={m.text} className="flex items-center gap-2.5 rounded-xl border border-border/40 bg-card/40 px-3 py-2.5 backdrop-blur-sm">
                    <m.icon className="h-4 w-4 text-secondary" />
                    <span className="text-sm font-medium text-foreground">{m.text}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Problem section */}
      <section className="py-20" id="how">
        <div className="mx-auto max-w-6xl px-4 sm:px-6">
          <div className="grid gap-12 lg:grid-cols-2 lg:items-center">
            <div>
              <div className="mb-3 inline-flex items-center gap-2 rounded-full bg-destructive/15 px-3 py-1 text-xs font-semibold text-destructive">
                <Zap className="h-3 w-3" /> The Problem
              </div>
              <h2 className="font-display text-4xl font-bold leading-tight text-foreground">Generic prep doesn't <span className="text-gradient">work anymore</span></h2>
              <p className="mt-4 text-foreground/80">Students preparing for campus placements lack personalized guidance and structured strategies. Existing resources serve everyone the same content — no skill analysis, no company-specific awareness.</p>
              <ul className="mt-6 space-y-3">
                {problems.map((p) => (
                  <li key={p} className="flex items-start gap-3 text-sm">
                    <span className="mt-0.5 inline-flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-destructive/20 text-destructive font-bold">✕</span>
                    <span className="text-foreground/85">{p}</span>
                  </li>
                ))}
              </ul>
            </div>
            <div className="relative">
              <div className="absolute -inset-6 rounded-3xl bg-gradient-hero opacity-30 blur-3xl animate-glow-pulse" />
              <div className="relative gradient-border p-8 shadow-elegant">
                <div className="mb-4 inline-flex items-center gap-2 rounded-full bg-accent/20 px-3 py-1 text-xs font-semibold text-accent">
                  <Target className="h-3 w-3" /> Our Solution
                </div>
                <h3 className="font-display text-2xl font-bold text-foreground">A personalized knowledge-aware system</h3>
                <div className="mt-5 space-y-4">
                  {[
                    "Adaptive assessment scores you across 4 dimensions",
                    "ML model predicts placement probability in real time",
                    "AI maps gaps against past company drive patterns",
                    "Generates a week-by-week roadmap unique to YOU",
                    "Voice AI mentor answers doubts instantly, anytime",
                  ].map((t) => (
                    <div key={t} className="flex items-start gap-3">
                      <CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-accent" />
                      <span className="text-sm text-foreground/90">{t}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Journey */}
      <section id="journey" className="border-t border-border/30 py-24">
        <div className="mx-auto max-w-6xl px-4 sm:px-6">
          <div className="mx-auto max-w-2xl text-center">
            <div className="mb-3 inline-flex items-center gap-2 rounded-full glass px-3 py-1 text-xs font-semibold text-accent">
              <Calendar className="h-3 w-3" /> Your Placement Journey
            </div>
            <h2 className="font-display text-4xl font-bold sm:text-5xl text-foreground">From confused to <span className="text-gradient">offer-ready</span></h2>
            <p className="mt-4 text-foreground/80">Four guided steps. Powered by AI. Trusted by students.</p>
          </div>
          <div className="mt-14 grid gap-6 md:grid-cols-2 lg:grid-cols-4">
            {journey.map((j, i) => {
              const Icon = j.icon;
              return (
                <div key={j.step} className="group relative animate-fade-in-up rounded-2xl border border-border/50 bg-card/40 p-6 backdrop-blur-sm hover-lift" style={{ animationDelay: `${i * 0.08}s` }}>
                  <div className="mb-4 flex items-center justify-between">
                    <div className="font-display text-3xl font-bold text-gradient opacity-80">{j.step}</div>
                    <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-hero shadow-glow">
                      <Icon className="h-5 w-5 text-primary-foreground" />
                    </div>
                  </div>
                  <h3 className="font-display text-lg font-bold text-foreground">{j.title}</h3>
                  <p className="mt-2 text-sm text-foreground/75">{j.desc}</p>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* Features */}
      <section id="features" className="border-t border-border/30 py-24">
        <div className="mx-auto max-w-6xl px-4 sm:px-6">
          <div className="mx-auto max-w-2xl text-center">
            <div className="mb-3 inline-flex items-center gap-2 rounded-full glass px-3 py-1 text-xs font-semibold text-primary-glow">
              <Sparkles className="h-3 w-3" /> 9 AI Modules · One Platform
            </div>
            <h2 className="font-display text-4xl font-bold sm:text-5xl text-foreground">Everything you need to <span className="text-gradient">get hired</span></h2>
            <p className="mt-4 text-foreground/80">A full AI-powered career operating system — built for final-year students.</p>
          </div>
          <div className="mt-16 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
            {features.map((f, i) => {
              const Icon = f.icon;
              return (
                <div key={f.title} className="group relative animate-fade-in-up overflow-hidden rounded-2xl border border-border/50 bg-card/40 p-7 backdrop-blur-sm transition-smooth hover:-translate-y-1 hover:border-primary/40 hover:shadow-elegant" style={{ animationDelay: `${i * 0.06}s` }}>
                  <div className="absolute inset-0 -z-10 bg-gradient-to-br from-primary/0 via-transparent to-secondary/0 opacity-0 transition-smooth group-hover:opacity-100 group-hover:from-primary/10 group-hover:to-secondary/10" />
                  <div className={`mb-5 inline-flex h-12 w-12 items-center justify-center rounded-xl bg-gradient-to-br ${f.color} shadow-glow`}>
                    <Icon className="h-6 w-6 text-primary-foreground" />
                  </div>
                  <h3 className="font-display text-xl font-bold text-foreground">{f.title}</h3>
                  <p className="mt-2 text-sm text-foreground/75 leading-relaxed">{f.desc}</p>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <section id="testimonials" className="border-t border-border/30 py-24">
        <div className="mx-auto max-w-6xl px-4 sm:px-6">
          <div className="mx-auto max-w-2xl text-center">
            <h2 className="font-display text-4xl font-bold sm:text-5xl text-foreground">Loved by <span className="text-gradient">future engineers</span></h2>
            <p className="mt-4 text-foreground/80">Real students. Real placements. Real results.</p>
          </div>
          <div className="mt-14 grid gap-6 md:grid-cols-3">
            {testimonials.map((t, i) => (
              <div key={t.name} className="rounded-2xl border border-border/50 bg-card/40 p-6 backdrop-blur-sm hover-lift animate-fade-in-up" style={{ animationDelay: `${i * 0.1}s` }}>
                <div className="mb-3 flex gap-0.5 text-accent">
                  {Array.from({ length: t.rating }).map((_, j) => <Star key={j} className="h-4 w-4 fill-current" />)}
                </div>
                <p className="text-sm text-foreground/90 leading-relaxed">"{t.text}"</p>
                <div className="mt-5 flex items-center gap-3">
                  <div className="flex h-10 w-10 items-center justify-center rounded-full bg-gradient-hero text-sm font-bold text-primary-foreground">{t.name[0]}</div>
                  <div>
                    <div className="text-sm font-semibold text-foreground">{t.name}</div>
                    <div className="text-xs text-foreground/70">{t.role}</div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-24">
        <div className="mx-auto max-w-4xl px-4 sm:px-6">
          <div className="relative overflow-hidden rounded-3xl bg-gradient-hero animate-gradient p-12 text-center shadow-elegant sm:p-16">
            <div className="pointer-events-none absolute -right-20 -top-20 h-60 w-60 rounded-full bg-white/15 blur-3xl animate-float" />
            <div className="pointer-events-none absolute -bottom-20 -left-20 h-60 w-60 rounded-full bg-white/15 blur-3xl animate-float" style={{ animationDelay: "2s" }} />
            <div className="relative">
              <div className="mx-auto inline-flex h-14 w-14 items-center justify-center rounded-2xl bg-white/20 backdrop-blur-sm">
                <TrendingUp className="h-7 w-7 text-primary-foreground" />
              </div>
              <h2 className="mt-5 font-display text-4xl font-bold text-primary-foreground sm:text-5xl">Ready to level up?</h2>
              <p className="mx-auto mt-4 max-w-xl text-primary-foreground/95">Join PlaceMentor AI Pro and turn months of confusion into a precise, AI-guided placement plan.</p>
              <Link to="/auth">
                <Button size="lg" variant="secondary" className="mt-8 bg-background text-foreground transition-bounce hover:scale-105">
                  Get started — it's free <ArrowRight className="ml-2 h-4 w-4" />
                </Button>
              </Link>
            </div>
          </div>
        </div>
      </section>

      <footer className="border-t border-border/30 py-8 text-center text-sm text-foreground/70">
        Built with 💜 for students. Powered by Lovable AI.
      </footer>
    </div>
  );
}
